---
- name: "backend directory creation"
  file:
    path: /ubuntu/home/backend
    state: directory

- name: "extract artifact"
  unarchive:
    src: artifact.tar.gz
    dest: /ubuntu/home/backend

- name: "install npm"
  become: true
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: "start node app"
  become: true
  shell: |
    cd /ubuntu/home/backend/dist
    pm2 stop default
    pm2 start -f main.js