---
- name: "backend directory creation"
  file:
    path: /ubuntu/home/backend
    state: directory

- name: "extract artifact"
  unarchive:
    src: artifact.tar.gz
    dest: /ubuntu/home/backend

- name: "installing node dependencies"
  shell: |
    cd /ubuntu/home/backend
    npm i

- name: "start node app"
  become: true
  shell: |
    cd /ubuntu/home/backend/dist
    pm2 stop default
    pm2 start -f main.js