---
- name: "backend directory creation"
  file:
    path: ~/backend
    state: directory

- name: "extract artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "installing node dependencies"
  shell: |
    cd ~/backend
    npm i

- name: "start node app"
  become: true
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start -f main.js